#spring.application.name=gateway
#server.port=8089
#
#eureka.client.service-url.default-zone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
#spring.cloud.gateway.discovery.locator.enabled=true
server:
  port: 8089

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: COMPANY-MS
            uri: http://company:8082
            predicates:
              - Path=/api/companies/**
          - id: JOB-MS
            uri: http://job:8081
            predicates:
              - Path=/api/jobs/**
          - id: REVIEW-MS
            uri: http://review:8083
            predicates:
              - Path=/api/reviews/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-reg:8761/eureka/

    register-with-eureka=true:
    fetch-registry=true:
