# Alap image (OpenJDK 21)
FROM openjdk:21-jdk-slim

# Munkakönyvtár beállítása
WORKDIR /app

# Másold a JAR fájlt a konténerbe
COPY target/REVIEW-MS-3.4.3.jar review.jar

# Indítsd el a JAR fájlt
CMD ["java", "-jar", "review.jar"]